### ISSUE TITLE
Will this copy entire directory tree at start if not on pod?

### ISSUE THREAD

**Issue by nickpapadonis** [sheldonjuncker/node-kubycat#1]
Just tried it out and it doesn't seem to do so. Thanks

**Comment by sheldonjuncker** [comment]
No, it wouldn't, but you should be able to `touch` the directory or the top-level files and folders, and they would sync. Some kind of `--sync-on-startup` flag or `kubycat sync-all` command would be useful and is actually something I've been wanting myself.

**Comment by sheldonjuncker** [comment]
I've added the configuration option `sync-on-start: boolean` which can be applied to any sync and will cause all of the files to be synced on startup of Kubycat. That should resolve this issue. Available in v1.2.4
